# Generated by Django 3.2.5 on 2022-07-17 09:18

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
