# Generated by Django 3.2.5 on 2022-07-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
